# SEO keywords and description for your site.
keywords = "hugo, tailwind, tailwindcss, hugo theme, hugo theme tailwind"
subtitle = "Example site for hugo-theme-tailwind"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "post"

jsonLD = true

showAuthor = true

[author]
  name = "Muhamad Rafli Maulana Rizki"
  email = "raflimaulanarizki8@gmail.com"
  link = 'https://gmail.com/'

[header]
  logo = "logo1.svg"

[footer]
  since = 2024
  poweredby = true

# giscus is comments system powered by GitHub Discussions
# generate configurations from https://giscus.app/
[giscus]
  enabled = true
  repo = "raflimaulanarizki/hugo-theme-tailwind"
  repoID = "R_kgDOMzEncw"
  category = "Announcements"
  categoryID = "DIC_kwDOMzEnc84Cik_L"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  lang = "en"


[social_media]
  [[social_media.items]]
    enabled = true
    title = 'LinkedIn'
    icon = 'brand-linkedin'
    link = 'https://www.linkedin.com/in/raflimaulanarizki/'

  [[social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/raflimaulanarizki'

  [[social_media.items]]
    enabled = true
    title = 'Email'
    icon = 'mail'
    link = 'https://mailhide.io/e/vhYpVUOr'


[pwa]
  enabled = true
  icon = "logo.png" # should be in assets
  icon_sizes = [192, 512]

  # will be used as the manifest.json file and merge the default one
  # https://developer.mozilla.org/en-US/docs/Web/Manifest
  # https://web.dev/add-manifest/
  [manifest]
  description = "Example site for hugo-theme-tailwind"
